language: generic
services:
- docker
env:
  global:
  - SR_VERSION=1.2.7 LENSES_CLI_VERSION=3.1.0 CONFLUENT_VERSION=5.1.0 KAFKA_VERSION=2.1.0
  - secure: Nhcd7XxQdrlXDGI317QiBAZ+cB9RbMNZWPb2ZLRwGfnNFoMJCotQbNx6roUuesIKC7tqN8unVFV2cAyjXiXaUWvP38CLxzQtn9eUe8eZNsxb0dsz+1W6dFZUgL0PV7ewK0iDV9JJwM0Y+ytNj2o81gulZLzs8S3N+xCYE2copYIvQR9U2tlsywnDURGfbLNkkmJhKTDSNZKBnK8qXYEi0SX1OalmrgcHWfB8slW5bg8GAi6QPRbj9WNS9LvP2LY2GtFeNSvE5rmlazKpoBL7Bi4Pq0E3Mvh0a0Qq+AswV6+mMj8dpsQ4So5OBE97WBTN8QnECfdLRHHFASKh9Mmlt0ps2zdoNbt3K8OePkAMmPk3xeGZ1svCFBcEC/CuCP5P0xmxyI/cCrrG5aQ2OerHBXdhpwTFFvx91tqTA7Zlu11qPFgriol5K+gUxNHjXdIkyjeGFvByea1xBPaZe0AFPW+5I/B06hQW2OE0kOXCalUcewNd111pFfHXbyDMXo0LhWB5A/+5tDn93118szl4QT7Js/TlteFk/0NRedJ089C3/DD2Q4Mi1PL31zj50j6Hecy9bM1sEV3Nt2PwLHuygXeDuFGzdbxUOd07VCqsdd7AvjwoOHbac2x5itPCZ9IZES7Xs/tR6gIzNOuXGWPPduofD4iEvgC9gsPq1YTmzWI=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
jobs:
  include:
  - stage: Publish
    deploy:
      on:
        tags: true
      provider: script
      script: bash ./publish-dockers ${TRAVIS_TAG} ${SR_VERSION} ${CONFLUENT_VERSION}
        ${KAFKA_VERSION} ${LENSES_CLI_VERSION}
