sudo: required

services:
  - docker
  
language: bash  

before_install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" 

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./build.sh
    fi
