language: generic
services:
- docker
env:
  global:
  - SR_VERSION=1.2.5 LENSES_CLI_VERSION=3.0.1 CONFLUENT_VERSION=5.1.0 KAFKA_VERSION=2.1.0
  - secure: n6u3R5U9XqcXKqQp8iM+zsdN7YQ3WKqMjWgBw6YFiQosZzMVNHVqck6TDnM0xsRqglpiBDDnLnDFGL1H/ulCJc+LTXciHGahoqIEqXQh8f0/FcfRfJQ+Gczot4KU/wIaVbI/jcDwjF5HcwnxYWfFYfauJSaJCnuNI0H8yQcD5piEwUHtkInc2BR+gTvRbizmCsFx59xoKL2i4Tjfo8jIH8oEKctSacYLEYJshMO092zpExv5SsHcu9ZOrAcFgrmdgQKc6O6BvHZaPY3Ny+erHguBMYZIU/a2E7yPkX/HUo1w851fdqxkzQeMWAfu7xQC80INBc7zw3IqidZ0G4qrCsTfAqzKZXaLdBdBs6AIxnfFph8ZH60xE3wZ6+buAErKBQ8i6W9x9OvVhttuw2UR+maKE7YN0OR5RCLoQu5iJF+Sbp7YS0nQwDRyihU5qdbBsb/kqpIYvU6YtNTkuqrNL8HftaOCIiGDEpq3ENN572CayWVsyFNRCNGScVlEhBOo/9YZJrSrmdKxzfy6Ha1+OxHzLjbd6i5PsJ1L4er8yuYVngCQGpEKJqgmb3qTN2WHP39pw2BAyZs15uBOn0vszwLu5UhxJAlL0wNQg8tM0P+8zEMmmohjh+AY/QWni/5KbSOB4bH4LANbtRtGWJYPryZSGlQKEGHMEesxuRwKKCU=
  - secure: Qxv2mHWut+Jpoy2KKnUs340v8nVH+nj6L14zpq79dOfb+F/nEhgfC+u3/pp0do+iGV8Arifr0Plf06dUtY3WC6Ua6A7kvMIibYrNuvKTD/mkffUfKQCtWG73GA4kEDaBo5YpP4gwycDiIk8NM1jx3xovpolg3kYhO+AFzmZ6oGcGq3HYI3kbyZfUoAMu3kfrXgd19jt+P1cj/NGoCbFo6/uBRwzaKyqLzc541m38JNVCoEN1FYIDsF/oVTi3EikLhC2YnuqOEQpiTU3P2b2ZL2YT1xE5JJ3K5VmQfaaLx45mY4Cihh18N5o6I9ExBmAgf+2Yjp6D+OqRdn5UUKDQAvSfJxayftHIvqF12IpR0s7iNrm6+sUPp1vtihpIw8RVbO86014hEciew2kjAZ9z7Yb60Xu4OI6d2/pDhy4+wgbJ5zIDWcWQihrwlj05xKkA+Yz61c/q0yf2Ns8dZ6JfUJD3NxrAFBRTKpBeniESLofQxT/mfBOiLEVZJAE9SwTu9+iPeGrm9YHkDdDqNNuTzWhrOBSddeuCDWvakmWorEebZd8QVGg16uFZokwYzJyIl4upgUK0eqAhx/FtO3qZC6l5KG8cyrn8bp24xPSxZWOaG5bXNxQFoY14xuGOIg8c0oxv6Iw8BjV05vbkQzJNRWLyn/yhIWbzpIBM02GyaCk=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
jobs:
  include:
  - stage: Publish
    deploy:
      on:
        tags: true
      provider: script
      script: bash ./publish-dockers ${TRAVIS_TAG} ${SR_VERSION} ${CONFLUENT_VERSION} ${KAFKA_VERSION} ${LENSES_CLI_VERSION}
