sudo: required

services:
	- docker
	
before_install:
	- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS" 

after_success:
	- if [ "$TRAVIS_BRANCH" == "master" ]; then
    		./buid.sh
