name: CI-BASE

# on:
  # push:
  #   branches: [ master ]
  # pull_request:
    # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Base
      run: bash build-dockers - - - - - - - - - dev

    - name: Build Connectors
      run: bash build-dockers - - - - - - - - - -
